### ISSUE TITLE
Implement Statements

### ISSUE THREAD

**Issue by Pyronix** [Pyronix/imp-go#1]
Statements are given here:
- https://sulzmann.github.io/ModelBasedSW/imp.html#(2)

Definition of Done:
- [x] Command Sequence
  - [x] Pretty
  - [x] Eval
  - [x] Check
  - [x] Tests 
- [x] Variable Declaration
  - [x] Pretty
  - [x] Eval
  - [x] Check
  - [x] Tests 
- [x] Variable Assignment
  - [x] Pretty
  - [x] Eval
  - [x] Check
  - [x] Tests 
- [x] While
  - [x] Pretty
  - [x] Eval
  - [x] Check
  - [x] Tests 
- [x] If-then-else
  - [x] Pretty
  - [x] Eval
  - [x] Check
  - [x] Tests 
- [x] Print
  - [x] Pretty
  - [x] Eval
  - [x] Check
  - [x] Tests 
- [x] Block
  - [x] Pretty
  - [x] Eval
  - [x] Check
  - [x] Tests 
- [x] Program
  - [x] Pretty
  - [x] Eval
  - [x] Check
  - [x] Tests

**Comment by n0ci** [comment]
Unittests are almost done. We still have to implement scoping and write some tests accordingly.
