### ISSUE TITLE
Implement Expressions

### ISSUE THREAD

**Issue by Pyronix** [Pyronix/imp-go#2]
List of expressions: https://sulzmann.github.io/ModelBasedSW/imp.html#(2)

Definition of Done:
- [x] Integers
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [x] Test
- [x] Booleans
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [x] Test
- [x] Addition
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [x] Test
- [x] Multiplication
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [x] Test
- [x] Disjunction
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [x] Test
- [x] Conjunction
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [x] Test
- [x] Negation
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [ ] Test
- [x] Equality test
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [x] Test
- [x] Lesser test
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [ ] Test
- [x] Grouping of expressions
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [x] Test
- [x] Variables
  - [x] Pretty
  - [x] Eval
  - [x] Infer 
  - [ ] Test

**Comment by n0ci** [comment]
Haken oben z.B. bei Integers heißt: ist in Bearbeitung
